# Generated by Django 4.2.8 on 2023-12-17 23:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sitios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="imgBanner",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="page_ptr",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="search_image",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="svgBanner",
        ),
        migrations.RemoveField(
            model_name="nservicios",
            name="page",
        ),
        migrations.RemoveField(
            model_name="nservicios",
            name="svg",
        ),
        migrations.DeleteModel(
            name="AQuien",
        ),
        migrations.DeleteModel(
            name="HomePage",
        ),
        migrations.DeleteModel(
            name="NServicios",
        ),
    ]
