# Generated by Django 4.2.8 on 2023-12-18 01:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_sitios_altura_sitios_cod_sitios_comuna_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Sitios",
            new_name="Sitio",
        ),
        migrations.AlterModelOptions(
            name="sitio",
            options={"verbose_name": "Sitio", "verbose_name_plural": "Sitios"},
        ),
    ]
