# Generated by Django 4.2.8 on 2023-12-18 02:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_rename_sitios_sitio_alter_sitio_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ITO",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        blank=True, max_length=25, null=True, verbose_name="Nombre"
                    ),
                ),
                (
                    "mobil",
                    models.CharField(
                        blank=True, max_length=11, null=True, verbose_name="Movil"
                    ),
                ),
                (
                    "correo",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="email"
                    ),
                ),
                (
                    "rut",
                    models.CharField(
                        blank=True, max_length=11, null=True, verbose_name="RUT"
                    ),
                ),
            ],
            options={
                "verbose_name": "ITO",
                "verbose_name_plural": "ITOs",
            },
        ),
        migrations.AlterField(
            model_name="sitio",
            name="altura",
            field=models.IntegerField(
                choices=[(24, "24"), (42, "42"), (48, "48")],
                default=42,
                verbose_name="Altura",
            ),
        ),
        migrations.AlterField(
            model_name="sitio",
            name="contratista",
            field=models.CharField(
                choices=[("MER", "MER"), ("AJ", "AJ")],
                default="MER",
                max_length=120,
                verbose_name="Contratista",
            ),
        ),
        migrations.AlterField(
            model_name="sitio",
            name="estado",
            field=models.CharField(
                choices=[
                    ("ASG", "Asignado"),
                    ("EJE", "Ejecución"),
                    ("PTG", "Postergado"),
                    ("CAN", "Cancelado"),
                ],
                default="EJE",
                max_length=10,
                verbose_name="Estado",
            ),
        ),
        migrations.AlterField(
            model_name="sitio",
            name="lat",
            field=models.FloatField(
                blank=True, max_length=10, null=True, verbose_name="Latitud"
            ),
        ),
        migrations.AlterField(
            model_name="sitio",
            name="lon",
            field=models.FloatField(
                blank=True, max_length=10, null=True, verbose_name="Longitud"
            ),
        ),
    ]
