# Generated by Django 4.2.8 on 2023-12-18 03:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_ito_alter_sitio_altura_alter_sitio_contratista_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ito",
            name="correo",
            field=models.CharField(
                blank=True, max_length=25, null=True, verbose_name="email"
            ),
        ),
        migrations.AlterField(
            model_name="ito",
            name="nombre",
            field=models.CharField(max_length=25, null=True, verbose_name="Nombre"),
        ),
    ]
