# Generated by Django 4.2.8 on 2023-12-18 03:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_alter_ito_correo_alter_ito_nombre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ito",
            name="correo",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="email"
            ),
        ),
    ]
