# Generated by Django 4.2.8 on 2023-12-18 03:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0008_alter_sitio_ito"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitio",
            name="ito",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="ITO"
            ),
        ),
    ]
