# Generated by Django 4.2.8 on 2023-12-18 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0009_alter_sitio_ito"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitio",
            name="ito",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="home.ito"
            ),
        ),
    ]
