# Generated by Django 4.2.8 on 2024-01-08 00:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0010_alter_sitio_ito"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitio",
            name="descripcion",
            field=models.TextField(blank=True, null=True, verbose_name="Descripción"),
        ),
        migrations.AddField(
            model_name="sitio",
            name="hormigonado",
            field=models.BooleanField(default=False, verbose_name="Hormigonado"),
        ),
        migrations.AddField(
            model_name="sitio",
            name="montado",
            field=models.BooleanField(default=False, verbose_name="Montado"),
        ),
        migrations.AlterField(
            model_name="sitio",
            name="estado",
            field=models.CharField(
                choices=[
                    ("ASG", "Asignado"),
                    ("EJE", "Ejecución"),
                    ("TER", "Terminado"),
                    ("PTG", "Postergado"),
                    ("CAN", "Cancelado"),
                ],
                default="EJE",
                max_length=10,
                verbose_name="Estado",
            ),
        ),
    ]
