# Generated by Django 4.2.8 on 2024-01-08 00:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0011_sitio_descripcion_sitio_hormigonado_sitio_montado_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitio",
            name="avance",
            field=models.IntegerField(default=0, verbose_name="Avance"),
        ),
    ]
