# Generated by Django 4.2.8 on 2024-01-08 03:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0012_sitio_avance"),
    ]

    operations = [
        migrations.CreateModel(
            name="PDFFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="pdfs/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="sitio",
            name="avance",
            field=models.IntegerField(default=0, verbose_name="%"),
        ),
        migrations.AlterField(
            model_name="sitio",
            name="hormigonado",
            field=models.BooleanField(default=False, verbose_name="Hor."),
        ),
        migrations.AlterField(
            model_name="sitio",
            name="montado",
            field=models.BooleanField(default=False, verbose_name="Mon."),
        ),
    ]
