# Generated by Django 4.2.8 on 2024-01-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0013_pdffile_alter_sitio_avance_alter_sitio_hormigonado_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reporte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archivo", models.FileField(upload_to="reportes/")),
            ],
        ),
        migrations.DeleteModel(
            name="PDFFile",
        ),
    ]
