# Generated by Django 4.2.8 on 2024-01-08 13:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0014_reporte_delete_pdffile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Reporte",
        ),
    ]
