# Generated by Django 4.2.8 on 2024-01-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0015_delete_reporte"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reporte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("pdf", models.FileField(upload_to="reportes/")),
            ],
        ),
    ]
