# Generated by Django 4.2.8 on 2024-01-08 14:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0017_rename_pdf_reporte_archivo_remove_reporte_titulo"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Reporte",
        ),
    ]
