# Generated by Django 4.2.8 on 2024-01-08 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0018_delete_reporte"),
    ]

    operations = [
        migrations.CreateModel(
            name="PDFFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="pdfs/")),
            ],
        ),
    ]
