# Generated by Django 4.2.8 on 2024-01-08 19:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0019_pdffile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PDFFile",
        ),
    ]
